AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  EasySchoolBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist.zip
      Handler: dist/serverless/serverless.handler
      Runtime: nodejs18.x
      Timeout: 900
      PackageType: Zip
      Environment:
        Variables:
          AWSAccessKeyId: !Ref AWSAccessKeyId
          AWSSecretAccessKey: !Ref AWSSecretAccessKey
          CYCLIC_DB: outstanding-necklace-frogCyclicDB
          CYCLIC_APP_ID: outstanding-necklace-frog
          CYCLIC_URL: https://outstanding-necklace-frog.cyclic.app
          CYCLIC_BUCKET_NAME: cyclic-outstanding-necklace-frog-eu-north-1
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{any+}
            Method: ANY
